spring:
    freemarker:
        cache: false
        template-loader-path: classpath:/freemarker/
        suffix: ftl
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/admin_web?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: root
            password: root
server:
    servlet:
        context-path: /dev-api
    port: 7777


logging:
    level:
        root: info
        me.liuwj.ktorm: debug
# generate swagger docs
swagger2:
    enable: true

# jwt 配置
jwt:
    header: authorization
    refreshToken: refresh_token
    secretKey: waibiwaibiwaibibabu
    expiration: 100
    accessTokenExpireTime: P30D
    refreshTokenExpireTime: PT8H
    refreshTokenExpireAppTime: P30D
    issuer: llh.com
    secret: areyougoodmalaixiya

code-gen-properties:
    auth: llh
    table-prefix: m_
    # 忽略字段。用于忽略公共的字段属性，用在查询时生成not in (xx)语句
    ignore-fields: id,create_at,updated_at,remove_flag,updated_by,created_by
    # 用于mysql与ktorm框架类型映射。
    # 仅列出常用的类型
    # 统一使用大写，方便进行比较
    # mysql中Boolean的规范为TINYINT(1)，需要添加额外的判断
    type-map:
        TINYINT: Int
        SMALLINT: Int
        MEDIUMINT: Int
        INT: Int
        INTEGER: Int
        BIGINT: Long
        FLOAT: Float
        DOUBLE: Double
        DECIMAL: java.math.BigDecimal

        CHAR: String
        VARCHAR: String
        TINYTEXT: String
        tinytext: String
        TEXT: String
        MEDIUMTEXT: String
        LONGTEXT: String

        DATE: java.time.LocalDate
        TIME: java.time.LocalTime
        YEAR: Int
        DATETIME: java.time.LocalDateTime
        TIMESTAMP: java.time.LocalDateTime
