spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/admin_web?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: root
            password: root
server:
    servlet:
        context-path: /dev-api
    port: 7777


logging:
    level:
        root: error
        me.liuwj.ktorm: debug
# generate swagger docs
swagger2:
    enable: true

# jwt 配置
jwt:
    header: authorization
    refreshToken: refresh_token
    secretKey: waibiwaibiwaibibabu
    expiration: 100
    accessTokenExpireTime: P30D
    refreshTokenExpireTime: PT8H
    refreshTokenExpireAppTime: P30D
    issuer: llh.com
    secret: areyougoodmalaixiya
